# BEGIN COPYRIGHT NOTICE
# Copyright 2026 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
{{ include "idol-library.aciserver.service" (dict 
    "root" .
    "component" .Values
    "ports" (fromYamlArray (include "idolstatsserver.customports" .))
    "destination" "idolstatsserver.service") }}
{{- define "idolstatsserver.service" -}}
{{/* Any Statistics Server specific merges to base template go here */}}
{{- end -}}
{{- define "idolstatsserver.customports" -}}
- port: {{ .Values.eventPort | int }}
  targetPort: events-port
  name: events-port
{{- end -}}