# BEGIN COPYRIGHT NOTICE
# Copyright 2026 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

{{ define "idolstatsserver.statefulset.base" -}}
{{/* specific merges to statefulset specification */}}
{{- $component := get . "component" | required "idolstatsserver.statefulset.base: missing component" -}}
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 300
  volumeClaimTemplates:
  - metadata:
      name: index
      labels: {{- include "idol-library.labels.volumeClaimTemplates" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ $component.statsServerStorageClass }}
      resources:
        requests:
          storage: {{ $component.statsServerVolumeSize }}
{{- end }}

{{- include "idol-library.util.merge" (dict
  "root" .
  "component" .Values
  "source" "idol-library.aciserver.statefulset.base.v1"
  "destination" "idolstatsserver.statefulset.base" 
  "containers" (list "idolstatsserver.container")
) -}}