# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE

# TODO: COMMENT
{{- $componentName := .Values.componentName | default (trimPrefix "idol-" .Values.name) -}}
{{- if eq .Values.idolImage.repo "agentstore" -}}
{{- $componentName = "agentstore" -}}
{{- end -}}

{{- include "idol-library.aciserver.defaultcfg" (dict 
    "root" .
    "component" .Values
    "componentName" $componentName
) -}}