# BEGIN COPYRIGHT NOTICE
# Copyright 2023 Open Text.
# 
# The only warranties for products and services of Open Text and its affiliates and licensors
# ("Open Text") are as may be set forth in the express warranty statements accompanying such
# products and services. Nothing herein should be construed as constituting an additional warranty.
# Open Text shall not be liable for technical or editorial errors or omissions contained herein.
# The information contained herein is subject to change without notice.
#
# END COPYRIGHT NOTICE
apiVersion: v2
name: idol-find
version: "0.3.3"
appVersion: "25.4.0"
description: Adds ``Find`` UI and supporting servers (Community, View)
dependencies:
- name: idol-library
  version: "~0.15.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: idol-licenseserver
  condition: idol-licenseserver.enabled
  version: "0.5.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: single-content
  condition: single-content.enabled
  version: "~0.11.0
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: idol-community
  condition: idol-community.enabled
  version: "~0.7.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
- name: idol-view
  condition: idol-view.enabled
  version: "~0.8.0"
  repository: https://raw.githubusercontent.com/opentext-idol/idol-containers-toolkit/main/helm
